name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - uses: actions/setup-go@v2
        with:
          python-version: "3.10"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/service-role/public-transit-service-function-role-poibofsl
          aws-region: ap-south-1

      - name: Build
        id: ecr
        run: |
          ./scripts/ecr.sh ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Deploy cloudformation stack
        id: public-transit-prod-lambda-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: public-transit-prod-lambda-stack
          template: infrastructure/lambda-template.yml
          capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
          timeout-in-minutes: "10"
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            ECRImageURI=${{ steps.ecr.outputs.ecr-image-uri }},            